In [1]:
# this is a audio classification project

In [2]:
import pandas as pd
import librosa 
import numpy as np
metadata=pd.read_csv("UrbanSound8K/metadata/UrbanSound8k.csv")
audio_dataset_path='UrbanSound8K/audio/'

In [31]:
metadata.shape[0]#  number of audio in dataset

8732

In [30]:
metadata.head()

,slice_file_name,fsID,start,end,salience,fold,classID,class
0,100032-3-0-0.wav,100032,0.0,0.317551,1,5,3,dog_bark
1,100263-2-0-117.wav,100263,58.5,62.500000,1,5,2,children_playing
2,100263-2-0-121.wav,100263,60.5,64.500000,1,5,2,children_playing
3,100263-2-0-126.wav,100263,63.0,67.000000,1,5,2,children_playing
4,100263-2-0-137.wav,100263,68.5,72.500000,1,5,2,children_playing

In [3]:
metadata["class"].value_counts()#10 classes

class
dog_bark            1000
children_playing    1000
air_conditioner     1000
street_music        1000
engine_idling       1000
jackhammer          1000
drilling            1000
siren                929
car_horn             429
gun_shot             374
Name: count, dtype: int64

In [4]:
 def feature_extractor(filename):
     audio,fs=librosa.load(filename)
     mfcc_feature_matrix=librosa.feature.mfcc(y=audio,sr=fs,n_mfcc=39)
     mfcc_scaled_feature=np.mean(mfcc_feature_matrix.T,axis=0) #[c1,c2,c3....c13]
     return mfcc_scaled_feature

In [5]:
from tqdm import tqdm
import os
tqdm(metadata.iterrows())# just checking how it works

0it [00:00, ?it/s]

In [6]:
extracted_feature=[]#[[audio1 features],[audio2 features]....]
for index_num,row in tqdm(metadata.iterrows()):
    file_name=os.path.join(os.path.abspath(audio_dataset_path),'fold'+str(row["fold"])+"/",str(row["slice_file_name"]))
    final_class_labels=row["class"]
    data= feature_extractor(file_name)
    extracted_feature.append([data,final_class_labels])

0it [00:00, ?it/s]
1it [00:08,  8.73s/it]
5it [00:08,  1.33s/it]
10it [00:08,  1.86it/s]
16it [00:09,  3.65it/s]
21it [00:09,  5.56it/s]
26it [00:09,  7.93it/s]
31it [00:09, 10.98it/s]
36it [00:09, 14.57it/s]
41it [00:09, 18.56it/s]
46it [00:09, 22.68it/s]
51it [00:09, 26.36it/s]
56it [00:09, 30.71it/s]
61it [00:10, 32.57it/s]
66it [00:10, 35.28it/s]
71it [00:10, 36.16it/s]
76it [00:10, 36.02it/s]
81it [00:10, 38.66it/s]
86it [00:10, 41.17it/s]
92it [00:10, 42.28it/s]
97it [00:10, 40.22it/s]
103it [00:11, 44.11it/s]
108it [00:11, 44.35it/s]
113it [00:11, 40.28it/s]
118it [00:11, 37.32it/s]
122it [00:11, 36.45it/s]
126it [00:11, 36.28it/s]
130it [00:11, 36.49it/s]
135it [00:11, 40.03it/s]
140it [00:12, 40.91it/s]
145it [00:12, 40.25it/s]
150it [00:12, 38.19it/s]
154it [00:12, 35.79it/s]
158it [00:12, 35.91it/s]
163it [00:12, 38.50it/s]
168it [00:12, 39.51it/s]
173it [00:12, 39.79it/s]
178it [00:13, 35.59it/s]
183it [00:13, 37.09it/s]
187it [00:13, 37.39it/s]
191it [00:13, 36.29it/s]
197it [00:13, 40.68it/s]
202it [00:13, 39.19it/s]
206it [00:13, 37.02it/s]
210it [00:13, 37.41it/s]
214it [00:14, 37.03it/s]
219it [00:14, 38.97it/s]
223it [00:14, 35.63it/s]
227it [00:14, 34.80it/s]
231it [00:14, 33.58it/s]
235it [00:14, 33.90it/s]
239it [00:14, 34.70it/s]
243it [00:14, 33.71it/s]
247it [00:15, 33.46it/s]
251it [00:15, 32.88it/s]
255it [00:15, 33.95it/s]
259it [00:15, 33.67it/s]
263it [00:15, 32.34it/s]
268it [00:15, 34.27it/s]
272it [00:15, 34.87it/s]
277it [00:15, 37.79it/s]
281it [00:15, 37.00it/s]
285it [00:16, 33.76it/s]
289it [00:16, 31.08it/s]
293it [00:16, 30.34it/s]
297it [00:16, 31.55it/s]
302it [00:16, 34.31it/s]
306it [00:16, 35.50it/s]
310it [00:16, 36.14it/s]
314it [00:17, 32.96it/s]
318it [00:17, 33.86it/s]
324it [00:17, 39.82it/s]
329it [00:17, 41.92it/s]
334it [00:17, 39.57it/s]
339it [00:17, 39.80it/s]
344it [00:17, 37.93it/s]
348it [00:17, 37.92it/s]
353it [00:17, 39.01it/s]
357it [00:18, 38.54it/s]
361it [00:18, 37.63it/s]
366it [00:18, 40.04it/s]
371it [00:18, 38.40it/s]
375it [00:18, 35.29it/s]
379it [00:18, 34.93it/s]
383it [00:18, 34.26it/s]
387it [00:18, 34.61it/s]
391it [00:19, 34.70it/s]
396it [00:19, 35.87it/s]
402it [00:19, 40.95it/s]
407it [00:19, 41.79it/s]
412it [00:19, 40.78it/s]
417it [00:19, 40.02it/s]
422it [00:19, 39.65it/s]
427it [00:19, 40.18it/s]
432it [00:20, 38.54it/s]
436it [00:20, 37.88it/s]
442it [00:20, 41.97it/s]
447it [00:20, 39.69it/s]
453it [00:20, 43.27it/s]
458it [00:20, 44.78it/s]
463it [00:20, 45.48it/s]
468it [00:20, 46.19it/s]
473it [00:20, 46.65it/s]
478it [00:21, 44.25it/s]
483it [00:21, 41.63it/s]
488it [00:21, 38.86it/s]
492it [00:21, 37.80it/s]
496it [00:21, 35.51it/s]
501it [00:21, 38.58it/s]
505it [00:21, 37.98it/s]
509it [00:21, 35.94it/s]
513it [00:22, 36.77it/s]
517it [00:22, 36.42it/s]
521it [00:22, 35.88it/s]
525it [00:22, 35.01it/s]
529it [00:22, 34.94it/s]
533it [00:22, 34.23it/s]
538it [00:22, 36.31it/s]
544it [00:22, 40.58it/s]
549it [00:23, 38.57it/s]
554it [00:23, 39.52it/s]
559it [00:23, 40.43it/s]
564it [00:23, 41.22it/s]
569it [00:23, 39.14it/s]
573it [00:23, 37.99it/s]
579it [00:23, 40.72it/s]
584it [00:23, 38.28it/s]
588it [00:24, 37.60it/s]
592it [00:24, 37.42it/s]
596it [00:24, 34.43it/s]
600it [00:24, 34.46it/s]
605it [00:24, 35.71it/s]
609it [00:24, 36.41it/s]
613it [00:24, 34.09it/s]
617it [00:24, 34.31it/s]
621it [00:24, 34.05it/s]
625it [00:25, 34.76it/s]
629it [00:25, 34.78it/s]
633it [00:25, 34.32it/s]
638it [00:25, 36.63it/s]
642it [00:25, 35.52it/s]
647it [00:25, 36.83it/s]
652it [00:25, 39.29it/s]
657it [00:25, 39.72it/s]
661it [00:26, 38.52it/s]
665it [00:26, 37.30it/s]
670it [00:26, 38.98it/s]
674it [00:26, 35.25it/s]
678it [00:26, 31.26it/s]
682it [00:26, 32.23it/s]
686it [00:26, 30.37it/s]
690it [00:26, 29.38it/s]
693it [00:27, 28.63it/s]
696it [00:27, 27.98it/s]
699it [00:27, 28.39it/s]
702it [00:27, 26.54it/s]
706it [00:27, 29.99it/s]
710it [00:27, 32.37it/s]
714it [00:27, 33.62it/s]
718it [00:27, 34.80it/s]
722it [00:28, 32.01it/s]
726it [00:28, 30.16it/s]
730it [00:28, 27.02it/s]
734it [00:28, 28.19it/s]
738it [00:28, 29.41it/s]
742it [00:28, 29.53it/s]
746it [00:28, 29.77it/s]
750it [00:29, 28.29it/s]
754it [00:29, 30.56it/s]
758it [00:29, 29.72it/s]
763it [00:29, 33.18it/s]
767it [00:29, 34.62it/s]
772it [00:29, 36.63it/s]
776it [00:29, 35.64it/s]
780it [00:29, 34.29it/s]
784it [00:30, 33.35it/s]
788it [00:30, 33.47it/s]
792it [00:30, 33.61it/s]
797it [00:30, 36.86it/s]
802it [00:30, 38.40it/s]
806it [00:30, 37.30it/s]
810it [00:30, 36.17it/s]
814it [00:30, 37.05it/s]
819it [00:30, 38.68it/s]
823it [00:31, 37.42it/s]
827it [00:31, 36.79it/s]
832it [00:31, 38.63it/s]
836it [00:31, 36.74it/s]
841it [00:31, 38.45it/s]
845it [00:31, 35.86it/s]
849it [00:31, 34.13it/s]
854it [00:31, 35.48it/s]
859it [00:32, 37.40it/s]
864it [00:32, 38.85it/s]
868it [00:32, 37.87it/s]
872it [00:32, 37.83it/s]
876it [00:32, 38.12it/s]
880it [00:32, 37.86it/s]
884it [00:32, 36.15it/s]
888it [00:32, 35.07it/s]
892it [00:32, 33.66it/s]
896it [00:33, 32.14it/s]
900it [00:33, 32.37it/s]
904it [00:33, 32.95it/s]
908it [00:33, 34.45it/s]
912it [00:33, 34.76it/s]
917it [00:33, 38.11it/s]
923it [00:33, 42.24it/s]
928it [00:33, 40.12it/s]
933it [00:34, 37.86it/s]
938it [00:34, 38.72it/s]
942it [00:34, 37.12it/s]
947it [00:34, 37.78it/s]
951it [00:34, 35.97it/s]
955it [00:34, 36.38it/s]
959it [00:34, 33.69it/s]
963it [00:34, 34.01it/s]
967it [00:35, 32.55it/s]
972it [00:35, 34.30it/s]
977it [00:35, 36.58it/s]
982it [00:35, 38.50it/s]
986it [00:35, 38.81it/s]
991it [00:35, 41.70it/s]
996it [00:35, 42.49it/s]
1001it [00:35, 42.12it/s]
1006it [00:35, 40.61it/s]
1011it [00:36, 38.07it/s]
1015it [00:36, 38.11it/s]
1019it [00:36, 38.21it/s]
1023it [00:36, 38.27it/s]
1027it [00:36, 34.18it/s]
1031it [00:36, 35.16it/s]
1036it [00:36, 38.40it/s]
1040it [00:36, 37.72it/s]
1044it [00:37, 36.48it/s]
1048it [00:37, 35.98it/s]
1053it [00:37, 38.40it/s]
1058it [00:37, 41.37it/s]
1063it [00:37, 36.88it/s]
1067it [00:37, 36.79it/s]
1072it [00:37, 38.00it/s]
1077it [00:37, 38.49it/s]
1081it [00:37, 38.15it/s]
1086it [00:38, 40.92it/s]
1091it [00:38, 41.63it/s]
1096it [00:38, 39.89it/s]
1101it [00:38, 38.31it/s]
1105it [00:38, 37.93it/s]
1109it [00:38, 35.14it/s]
1113it [00:38, 34.04it/s]
1117it [00:38, 33.94it/s]
1121it [00:39, 35.24it/s]
1125it [00:39, 35.00it/s]
1130it [00:39, 36.69it/s]
1134it [00:39, 36.91it/s]
1138it [00:39, 35.61it/s]
1142it [00:39, 34.93it/s]
1147it [00:39, 37.46it/s]
1151it [00:39, 35.90it/s]
1155it [00:40, 36.49it/s]
1160it [00:40, 38.06it/s]
1164it [00:40, 37.35it/s]
1168it [00:40, 37.79it/s]
1173it [00:40, 41.05it/s]
1179it [00:40, 42.41it/s]
1184it [00:40, 38.54it/s]
1188it [00:40, 36.68it/s]
1192it [00:40, 36.48it/s]
1196it [00:41, 36.21it/s]
1200it [00:41, 34.66it/s]
1204it [00:41, 33.63it/s]
1208it [00:41, 35.27it/s]
1213it [00:41, 36.15it/s]
1217it [00:41, 36.82it/s]
1221it [00:41, 33.84it/s]
1225it [00:41, 30.78it/s]
1229it [00:42, 31.10it/s]
1233it [00:42, 31.96it/s]
1237it [00:42, 33.41it/s]
1241it [00:42, 33.45it/s]
1246it [00:42, 35.81it/s]
1250it [00:42, 34.14it/s]
1254it [00:42, 33.98it/s]
1259it [00:42, 37.01it/s]
1263it [00:43, 36.03it/s]
1267it [00:43, 35.30it/s]
1272it [00:43, 36.66it/s]
1276it [00:43, 35.37it/s]
1280it [00:43, 35.92it/s]
1284it [00:43, 34.92it/s]
1288it [00:43, 33.84it/s]
1292it [00:43, 34.42it/s]
1296it [00:43, 34.59it/s]
1300it [00:44, 35.03it/s]
1305it [00:44, 35.42it/s]
1309it [00:44, 36.09it/s]
1315it [00:44, 40.09it/s]
1320it [00:44, 38.67it/s]
1325it [00:44, 40.14it/s]
1330it [00:44, 38.20it/s]
1335it [00:44, 39.28it/s]
1341it [00:45, 41.73it/s]
1346it [00:45, 40.61it/s]
1351it [00:45, 38.67it/s]
1355it [00:45, 37.14it/s]
1359it [00:45, 35.30it/s]
1363it [00:45, 34.84it/s]
1369it [00:45, 38.39it/s]
1374it [00:46, 37.61it/s]
1378it [00:46, 34.60it/s]
1382it [00:46, 34.41it/s]
1386it [00:46, 34.33it/s]
1390it [00:46, 32.14it/s]
1394it [00:46, 32.28it/s]
1399it [00:46, 34.20it/s]
1404it [00:46, 36.19it/s]
1408it [00:47, 36.67it/s]
1412it [00:47, 37.02it/s]
1417it [00:47, 37.61it/s]
1422it [00:47, 39.87it/s]
1427it [00:47, 40.53it/s]
1432it [00:47, 42.38it/s]
1438it [00:47, 45.17it/s]
1443it [00:47, 42.42it/s]
1448it [00:47, 42.93it/s]
1453it [00:48, 41.39it/s]
1458it [00:48, 42.24it/s]
1463it [00:48, 41.88it/s]
1468it [00:48, 43.22it/s]
1473it [00:48, 41.30it/s]
1479it [00:48, 43.92it/s]
1484it [00:48, 43.07it/s]
1489it [00:48, 44.65it/s]
1494it [00:49, 44.55it/s]
1499it [00:49, 40.41it/s]
1504it [00:49, 36.29it/s]
1508it [00:49, 34.57it/s]
1512it [00:49, 34.23it/s]
1516it [00:49, 35.03it/s]
1520it [00:49, 35.99it/s]
1524it [00:49, 36.75it/s]
1528it [00:50, 36.18it/s]
1532it [00:50, 35.87it/s]
1536it [00:50, 36.71it/s]
1540it [00:50, 36.95it/s]
1544it [00:50, 36.20it/s]
1548it [00:50, 36.68it/s]
1552it [00:50, 37.50it/s]
1556it [00:50, 35.74it/s]
1561it [00:50, 36.41it/s]
1565it [00:51, 36.35it/s]
1569it [00:51, 36.46it/s]
1573it [00:51, 35.88it/s]
1578it [00:51, 36.76it/s]
1582it [00:51, 36.18it/s]
1587it [00:51, 38.86it/s]
1593it [00:51, 41.29it/s]
1598it [00:51, 43.20it/s]
1603it [00:51, 43.20it/s]
1608it [00:52, 39.58it/s]
1613it [00:52, 38.97it/s]
1618it [00:52, 40.92it/s]
1623it [00:52, 38.94it/s]
1628it [00:52, 39.97it/s]
1633it [00:52, 41.51it/s]
1638it [00:52, 40.35it/s]
1643it [00:52, 42.56it/s]
1648it [00:53, 39.89it/s]
1653it [00:53, 37.67it/s]
1657it [00:53, 37.80it/s]
1662it [00:53, 38.68it/s]
1666it [00:53, 38.45it/s]
1670it [00:53, 37.09it/s]
1674it [00:53, 36.17it/s]
1678it [00:53, 32.17it/s]
1682it [00:54, 29.56it/s]
1686it [00:54, 30.21it/s]
1690it [00:54, 30.45it/s]
1694it [00:54, 30.46it/s]
1698it [00:54, 31.42it/s]
1702it [00:54, 31.67it/s]
1706it [00:54, 31.68it/s]
1710it [00:55, 32.09it/s]
1714it [00:55, 32.25it/s]
1718it [00:55, 33.20it/s]
1722it [00:55, 34.19it/s]
1726it [00:55, 33.86it/s]
1730it [00:55, 32.20it/s]
1735it [00:55, 35.60it/s]
1739it [00:55, 34.89it/s]
1743it [00:55, 33.93it/s]
1747it [00:56, 33.42it/s]
1751it [00:56, 34.92it/s]
1756it [00:56, 37.31it/s]
1760it [00:56, 35.11it/s]
1764it [00:56, 34.48it/s]
1769it [00:56, 38.13it/s]
1773it [00:56, 38.49it/s]
1778it [00:56, 38.84it/s]
1782it [00:57, 37.30it/s]
1787it [00:57, 38.26it/s]
1791it [00:57, 37.30it/s]
1795it [00:57, 35.37it/s]
1799it [00:57, 34.73it/s]
1803it [00:57, 34.17it/s]
1807it [00:57, 32.68it/s]
1812it [00:57, 36.00it/s]
1817it [00:57, 39.33it/s]
1822it [00:58, 41.51it/s]
1827it [00:58, 40.68it/s]
1832it [00:58, 34.68it/s]
1836it [00:58, 34.43it/s]
1840it [00:58, 33.78it/s]
1844it [00:58, 33.08it/s]
1848it [00:58, 33.93it/s]
1853it [00:59, 36.55it/s]
1857it [00:59, 35.98it/s]
1861it [00:59, 35.96it/s]
1866it [00:59, 37.28it/s]
1870it [00:59, 35.08it/s]
1874it [00:59, 35.69it/s]
1878it [00:59, 35.33it/s]
1882it [00:59, 33.73it/s]
1886it [00:59, 34.10it/s]
1890it [01:00, 34.66it/s]
1894it [01:00, 33.66it/s]
1898it [01:00, 32.67it/s]
1902it [01:00, 32.68it/s]
1907it [01:00, 35.96it/s]
1911it [01:00, 36.50it/s]
1915it [01:00, 37.08it/s]
1919it [01:00, 37.78it/s]
1924it [01:00, 39.96it/s]
1929it [01:01, 40.22it/s]
1934it [01:01, 41.33it/s]
1939it [01:01, 40.33it/s]
1944it [01:01, 40.21it/s]
1949it [01:01, 37.38it/s]
1953it [01:01, 35.53it/s]
1958it [01:01, 38.67it/s]
1966it [01:01, 48.16it/s]
1971it [01:02, 48.09it/s]
1976it [01:02, 48.45it/s]
1981it [01:02, 47.50it/s]
1986it [01:02, 43.94it/s]
1991it [01:02, 41.33it/s]
1996it [01:02, 38.66it/s]
2000it [01:02, 36.92it/s]
2004it [01:03, 31.05it/s]
2009it [01:03, 33.76it/s]
2013it [01:03, 34.90it/s]
2018it [01:03, 37.22it/s]
2023it [01:03, 38.59it/s]
2028it [01:03, 40.07it/s]
2033it [01:03, 40.41it/s]
2038it [01:03, 42.80it/s]
2044it [01:03, 47.15it/s]
2050it [01:04, 48.16it/s]
2056it [01:04, 49.07it/s]
2063it [01:04, 51.25it/s]
2069it [01:04, 41.74it/s]
2074it [01:04, 37.22it/s]
2078it [01:04, 36.81it/s]
2082it [01:04, 36.67it/s]
2088it [01:05, 40.81it/s]
2093it [01:05, 39.03it/s]
2098it [01:05, 38.08it/s]
2102it [01:05, 36.62it/s]
2106it [01:05, 35.21it/s]
2111it [01:05, 36.91it/s]
2115it [01:05, 37.69it/s]
2119it [01:05, 34.84it/s]
2124it [01:05, 38.67it/s]
2128it [01:06, 35.87it/s]
2132it [01:06, 35.71it/s]
2136it [01:06, 35.48it/s]
2140it [01:06, 33.40it/s]
2144it [01:06, 29.14it/s]
2148it [01:06, 29.83it/s]
2152it [01:06, 31.91it/s]
2156it [01:07, 32.90it/s]
2160it [01:07, 33.31it/s]
2164it [01:07, 34.46it/s]
2169it [01:07, 38.24it/s]
2174it [01:07, 41.13it/s]
2179it [01:07, 41.58it/s]
2184it [01:07, 38.93it/s]
2188it [01:07, 38.37it/s]
2192it [01:07, 38.36it/s]
2196it [01:08, 35.09it/s]
2200it [01:08, 35.59it/s]
2204it [01:08, 33.26it/s]
2208it [01:08, 34.23it/s]
2214it [01:08, 38.10it/s]
2218it [01:08, 37.65it/s]
2222it [01:08, 36.50it/s]
2226it [01:08, 36.47it/s]
2231it [01:08, 39.43it/s]
2236it [01:09, 39.78it/s]
2240it [01:09, 39.05it/s]
2244it [01:09, 37.78it/s]
2249it [01:09, 39.03it/s]
2253it [01:09, 37.64it/s]
2257it [01:09, 36.55it/s]
2261it [01:09, 36.04it/s]
2265it [01:09, 33.98it/s]
2269it [01:10, 31.72it/s]
2273it [01:10, 30.79it/s]
2277it [01:10, 32.37it/s]
2282it [01:10, 35.06it/s]
2287it [01:10, 37.05it/s]
2291it [01:10, 37.08it/s]
2295it [01:10, 34.21it/s]
2300it [01:10, 36.65it/s]
2305it [01:11, 38.50it/s]
2311it [01:11, 43.63it/s]
2316it [01:11, 44.38it/s]
2321it [01:11, 38.58it/s]
2326it [01:11, 34.78it/s]
2330it [01:11, 31.85it/s]
2334it [01:11, 29.76it/s]
2338it [01:12, 28.23it/s]
2341it [01:12, 28.00it/s]
2345it [01:12, 30.61it/s]
2349it [01:12, 29.78it/s]
2353it [01:12, 30.01it/s]
2357it [01:12, 32.33it/s]
2361it [01:12, 33.27it/s]
2365it [01:12, 33.88it/s]
2369it [01:13, 33.45it/s]
2373it [01:13, 34.93it/s]
2378it [01:13, 37.78it/s]
2382it [01:13, 37.28it/s]
2386it [01:13, 37.77it/s]
2390it [01:13, 37.42it/s]
2394it [01:13, 38.12it/s]
2400it [01:13, 40.83it/s]
2405it [01:13, 36.08it/s]
2409it [01:14, 35.33it/s]
2413it [01:14, 34.97it/s]
2418it [01:14, 36.93it/s]
2423it [01:14, 37.63it/s]
2428it [01:14, 39.82it/s]
2434it [01:14, 44.22it/s]
2439it [01:14, 38.73it/s]
2444it [01:14, 37.54it/s]
2448it [01:15, 37.01it/s]
2453it [01:15, 39.24it/s]
2458it [01:15, 38.09it/s]
2462it [01:15, 37.76it/s]
2467it [01:15, 38.51it/s]
2471it [01:15, 38.71it/s]
2475it [01:15, 38.49it/s]
2480it [01:15, 41.28it/s]
2485it [01:15, 42.65it/s]
2490it [01:16, 43.12it/s]
2495it [01:16, 42.96it/s]
2500it [01:16, 41.52it/s]
2505it [01:16, 37.59it/s]
2510it [01:16, 38.99it/s]
2515it [01:16, 41.42it/s]
2520it [01:16, 41.92it/s]
2525it [01:16, 40.83it/s]
2530it [01:17, 35.40it/s]
2534it [01:17, 31.29it/s]
2538it [01:17, 29.27it/s]
2542it [01:17, 29.02it/s]
2546it [01:17, 30.27it/s]
2550it [01:17, 31.43it/s]
2554it [01:17, 32.03it/s]
2558it [01:18, 32.17it/s]
2562it [01:18, 31.08it/s]
2566it [01:18, 30.32it/s]
2570it [01:18, 30.06it/s]
2575it [01:18, 33.64it/s]
2579it [01:18, 34.83it/s]
2584it [01:18, 37.40it/s]
2588it [01:18, 36.25it/s]
2594it [01:19, 40.38it/s]
2600it [01:19, 44.36it/s]
2606it [01:19, 48.14it/s]
2611it [01:19, 48.11it/s]
2616it [01:19, 44.51it/s]
2621it [01:19, 42.80it/s]
2626it [01:19, 37.32it/s]
2631it [01:19, 38.60it/s]
2635it [01:20, 38.59it/s]
2639it [01:20, 38.16it/s]
2643it [01:20, 34.73it/s]
2647it [01:20, 33.84it/s]
2651it [01:20, 34.15it/s]
2655it [01:20, 33.91it/s]
2659it [01:20, 31.76it/s]
2663it [01:21, 29.29it/s]
2666it [01:21, 28.95it/s]
2670it [01:21, 30.01it/s]
2674it [01:21, 30.37it/s]
2678it [01:21, 30.48it/s]
2682it [01:21, 31.09it/s]
2686it [01:21, 23.50it/s]
2690it [01:21, 25.79it/s]
2694it [01:22, 27.91it/s]
2698it [01:22, 28.69it/s]
2702it [01:22, 29.39it/s]
2706it [01:22, 29.33it/s]
2710it [01:22, 30.99it/s]
2714it [01:22, 33.12it/s]
2718it [01:22, 33.19it/s]
2722it [01:22, 33.30it/s]
2726it [01:23, 34.00it/s]
2730it [01:23, 35.36it/s]
2734it [01:23, 34.93it/s]
2738it [01:23, 34.70it/s]
2742it [01:23, 34.69it/s]
2746it [01:23, 33.62it/s]
2750it [01:23, 35.06it/s]
2754it [01:23, 34.47it/s]
2758it [01:23, 35.86it/s]
2762it [01:24, 33.89it/s]
2766it [01:24, 29.28it/s]
2770it [01:24, 29.74it/s]
2774it [01:24, 28.00it/s]
2777it [01:24, 27.11it/s]
2781it [01:24, 29.05it/s]
2784it [01:24, 29.19it/s]
2788it [01:25, 29.70it/s]
2791it [01:25, 29.29it/s]
2794it [01:25, 28.21it/s]
2797it [01:25, 28.32it/s]
2800it [01:25, 27.91it/s]
2803it [01:25, 26.91it/s]
2806it [01:25, 26.48it/s]
2809it [01:25, 25.35it/s]
2813it [01:25, 28.55it/s]
2818it [01:26, 33.71it/s]
2822it [01:26, 33.19it/s]
2826it [01:26, 31.29it/s]
2832it [01:26, 36.48it/s]
2836it [01:26, 37.10it/s]
2840it [01:26, 37.18it/s]
2844it [01:26, 36.10it/s]
2849it [01:26, 37.46it/s]
2853it [01:27, 29.30it/s]
2857it [01:27, 23.26it/s]
2860it [01:27, 21.06it/s]
2863it [01:27, 19.14it/s]
2866it [01:27, 18.54it/s]
2869it [01:28, 20.56it/s]
2872it [01:28, 22.42it/s]
2876it [01:28, 24.67it/s]
2880it [01:28, 27.09it/s]
2884it [01:28, 28.72it/s]
2888it [01:28, 27.98it/s]
2892it [01:28, 29.50it/s]
2896it [01:28, 30.09it/s]
2900it [01:29, 31.86it/s]
2904it [01:29, 29.96it/s]
2908it [01:29, 27.98it/s]
2911it [01:29, 26.33it/s]
2914it [01:29, 25.16it/s]
2917it [01:29, 23.83it/s]
2920it [01:29, 22.68it/s]
2923it [01:30, 22.72it/s]
2926it [01:30, 23.44it/s]
2929it [01:30, 23.78it/s]
2932it [01:30, 24.43it/s]
2935it [01:30, 23.81it/s]
2938it [01:30, 23.62it/s]
2941it [01:30, 23.26it/s]
2944it [01:30, 24.30it/s]
2948it [01:31, 27.12it/s]
2951it [01:31, 26.28it/s]
2954it [01:31, 26.27it/s]
2957it [01:31, 26.07it/s]
2960it [01:31, 25.94it/s]
2963it [01:31, 26.28it/s]
2966it [01:31, 24.21it/s]
2969it [01:31, 23.66it/s]
2972it [01:31, 25.21it/s]
2976it [01:32, 29.07it/s]
2981it [01:32, 34.03it/s]
2986it [01:32, 36.60it/s]
2991it [01:32, 39.69it/s]
2997it [01:32, 43.73it/s]
3002it [01:32, 43.50it/s]
3008it [01:32, 47.14it/s]
3014it [01:32, 49.76it/s]
3020it [01:33, 45.96it/s]
3025it [01:33, 40.01it/s]
3030it [01:33, 36.98it/s]
3034it [01:33, 35.40it/s]
3038it [01:33, 35.62it/s]
3042it [01:33, 33.96it/s]
3046it [01:33, 32.21it/s]
3050it [01:33, 31.78it/s]
3054it [01:34, 32.71it/s]
3060it [01:34, 38.62it/s]
3065it [01:34, 39.76it/s]
3070it [01:34, 35.28it/s]
3074it [01:34, 34.71it/s]
3078it [01:34, 35.96it/s]
3082it [01:34, 36.25it/s]
3088it [01:34, 39.88it/s]
3093it [01:35, 37.85it/s]
3098it [01:35, 38.90it/s]
3102it [01:35, 37.50it/s]
3106it [01:35, 36.34it/s]
3110it [01:35, 35.89it/s]
3114it [01:35, 34.99it/s]
3118it [01:35, 34.23it/s]
3122it [01:35, 33.53it/s]
3126it [01:36, 32.50it/s]
3130it [01:36, 31.06it/s]
3134it [01:36, 30.05it/s]
3138it [01:36, 30.69it/s]
3143it [01:36, 34.36it/s]
3147it [01:36, 35.07it/s]
3151it [01:36, 35.21it/s]
3155it [01:36, 33.75it/s]
3159it [01:37, 28.56it/s]
3164it [01:37, 33.15it/s]
3168it [01:37, 30.36it/s]
3173it [01:37, 33.36it/s]
3178it [01:37, 36.32it/s]
3182it [01:37, 32.73it/s]
3186it [01:37, 32.98it/s]
3191it [01:38, 36.22it/s]
3195it [01:38, 33.80it/s]
3199it [01:38, 32.74it/s]
3204it [01:38, 35.14it/s]
3208it [01:38, 32.55it/s]
3212it [01:38, 31.62it/s]
3216it [01:38, 30.59it/s]
3220it [01:38, 29.81it/s]
3224it [01:39, 29.32it/s]
3228it [01:39, 31.22it/s]
3232it [01:39, 30.83it/s]
3236it [01:39, 29.10it/s]
3239it [01:39, 28.86it/s]
3242it [01:39, 27.87it/s]
3245it [01:39, 27.54it/s]
3248it [01:39, 27.89it/s]
3252it [01:40, 28.66it/s]
3256it [01:40, 30.56it/s]
3260it [01:40, 29.91it/s]
3264it [01:40, 29.65it/s]
3268it [01:40, 30.52it/s]
3272it [01:40, 32.05it/s]
3276it [01:40, 32.55it/s]
3280it [01:40, 31.58it/s]
3284it [01:41, 33.02it/s]
3288it [01:41, 33.63it/s]
3292it [01:41, 31.94it/s]
3296it [01:41, 31.07it/s]
3301it [01:41, 34.25it/s]
3305it [01:41, 34.63it/s]
3309it [01:41, 33.53it/s]
3314it [01:41, 36.37it/s]
3318it [01:42, 36.34it/s]
3322it [01:42, 36.06it/s]
3326it [01:42, 32.94it/s]
3330it [01:42, 32.40it/s]
3334it [01:42, 32.86it/s]
3338it [01:42, 29.89it/s]
3342it [01:42, 30.01it/s]
3346it [01:42, 31.55it/s]
3350it [01:43, 31.30it/s]
3354it [01:43, 29.54it/s]
3358it [01:43, 29.30it/s]
3362it [01:43, 29.73it/s]
3365it [01:43, 29.29it/s]
3368it [01:43, 28.98it/s]
3371it [01:43, 27.59it/s]
3374it [01:43, 26.79it/s]
3377it [01:44, 26.63it/s]
3380it [01:44, 26.77it/s]
3384it [01:44, 27.78it/s]
3387it [01:44, 28.10it/s]

In [7]:
extracted_feature[0]

[array([-2.1193698e+02,  6.2581207e+01, -1.2281315e+02, -6.0745293e+01,
        -1.3893760e+01, -2.9789831e+01, -3.9788749e+00,  1.1682742e+01,
         1.2963828e+01,  8.3364210e+00, -6.5298195e+00, -2.9961064e+00,
        -1.2887950e+01,  5.8859329e+00, -2.4752252e+00, -4.4083114e+00,
        -1.5014478e+01, -9.4399697e-01, -2.5799108e+00,  6.0982971e+00,
        -1.0786229e+01, -8.0634775e+00,  5.8440900e+00, -3.1225369e+00,
        -5.9842286e+00, -7.9944439e-02, -3.6870899e+00,  4.7476764e+00,
        -6.5300946e+00, -5.0838842e+00,  4.8772502e-01,  7.5108857e+00,
        -8.8536072e-01,  2.3938138e+00, -6.3923712e+00, -2.1318593e+00,
         2.2760150e+00, -7.9108340e-01, -1.5400677e+00], dtype=float32),
 'dog_bark']

In [8]:
df=pd.DataFrame(extracted_feature,columns=["feature","class"])

In [9]:
df.head()

                                             feature             class
0  [-211.93698, 62.581207, -122.81315, -60.745293...          dog_bark
1  [-417.0052, 99.336624, -42.995586, 51.073326, ...  children_playing
2  [-452.39316, 112.36253, -37.57807, 43.19586, 8...  children_playing
3  [-406.47922, 91.1966, -25.043558, 42.78452, 11...  children_playing
4  [-439.63873, 103.86223, -42.65879, 50.690277, ...  children_playing

In [10]:
#expending features into particular list 
feature_df=pd.DataFrame(df["feature"].tolist())

In [11]:
feature_df.head()

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,-211.936981,62.581207,-122.813148,-60.745293,-13.893760,-29.789831,-3.978875,11.682742,12.963828,8.336421,...,-5.083884,0.487725,7.510886,-0.885361,2.393814,-6.392371,-2.131859,2.276015,-0.791083,-1.540068
1,-417.005188,99.336624,-42.995586,51.073326,9.853778,7.969693,11.197088,1.929117,7.030397,4.270228,...,0.870299,-1.250227,2.277220,-1.539242,0.767109,-0.878724,0.908738,-2.681854,1.706798,-1.793607
2,-452.393158,112.362534,-37.578072,43.195862,8.631845,15.379366,16.882149,1.233047,6.833122,3.900115,...,2.363491,0.067258,-0.154540,-5.285954,-0.790016,-2.979211,-0.202845,-3.088082,3.808014,-0.090056
3,-406.479218,91.196602,-25.043558,42.784519,11.586843,5.054164,12.431632,-1.599948,6.656064,1.442355,...,-1.278362,-4.996307,1.279155,0.635734,1.414131,-2.831120,1.808179,-2.178431,-0.436480,-3.051344
4,-439.638733,103.862228,-42.658791,50.690277,12.209422,15.873465,11.729268,1.533585,11.292244,2.548621,...,0.117671,-2.928395,-0.774089,-0.985247,2.566369,-2.976879,1.071741,-1.825602,3.291397,-0.169670

In [12]:
class_df=pd.DataFrame(df["class"],columns=["class"])

In [13]:
df=pd.concat([feature_df,class_df],axis=1)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8732 entries, 0 to 8731
Data columns (total 40 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       8732 non-null   float32
 1   1       8732 non-null   float32
 2   2       8732 non-null   float32
 3   3       8732 non-null   float32
 4   4       8732 non-null   float32
 5   5       8732 non-null   float32
 6   6       8732 non-null   float32
 7   7       8732 non-null   float32
 8   8       8732 non-null   float32
 9   9       8732 non-null   float32
 10  10      8732 non-null   float32
 11  11      8732 non-null   float32
 12  12      8732 non-null   float32
 13  13      8732 non-null   float32
 14  14      8732 non-null   float32
 15  15      8732 non-null   float32
 16  16      8732 non-null   float32
 17  17      8732 non-null   float32
 18  18      8732 non-null   float32
 19  19      8732 non-null   float32
 20  20      8732 non-null   float32
 21  21      8732 non-null   float32
 22  22      8732 non-null   float32
 23  23      8732 non-null   float32
 24  24      8732 non-null   float32
 25  25      8732 non-null   float32
 26  26      8732 non-null   float32
 27  27      8732 non-null   float32
 28  28      8732 non-null   float32
 29  29      8732 non-null   float32
 30  30      8732 non-null   float32
 31  31      8732 non-null   float32
 32  32      8732 non-null   float32
 33  33      8732 non-null   float32
 34  34      8732 non-null   float32
 35  35      8732 non-null   float32
 36  36      8732 non-null   float32
 37  37      8732 non-null   float32
 38  38      8732 non-null   float32
 39  class   8732 non-null   object
dtypes: float32(39), object(1)
memory usage: 1.4+ MB

In [15]:
X=df.iloc[:,:39]
Y=df["class"]
X.head()

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,-211.936981,62.581207,-122.813148,-60.745293,-13.893760,-29.789831,-3.978875,11.682742,12.963828,8.336421,...,-5.083884,0.487725,7.510886,-0.885361,2.393814,-6.392371,-2.131859,2.276015,-0.791083,-1.540068
1,-417.005188,99.336624,-42.995586,51.073326,9.853778,7.969693,11.197088,1.929117,7.030397,4.270228,...,0.870299,-1.250227,2.277220,-1.539242,0.767109,-0.878724,0.908738,-2.681854,1.706798,-1.793607
2,-452.393158,112.362534,-37.578072,43.195862,8.631845,15.379366,16.882149,1.233047,6.833122,3.900115,...,2.363491,0.067258,-0.154540,-5.285954,-0.790016,-2.979211,-0.202845,-3.088082,3.808014,-0.090056
3,-406.479218,91.196602,-25.043558,42.784519,11.586843,5.054164,12.431632,-1.599948,6.656064,1.442355,...,-1.278362,-4.996307,1.279155,0.635734,1.414131,-2.831120,1.808179,-2.178431,-0.436480,-3.051344
4,-439.638733,103.862228,-42.658791,50.690277,12.209422,15.873465,11.729268,1.533585,11.292244,2.548621,...,0.117671,-2.928395,-0.774089,-0.985247,2.566369,-2.976879,1.071741,-1.825602,3.291397,-0.169670

In [16]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
le=LabelEncoder()
Y=le.fit_transform(Y)
Y=to_categorical(Y)
Y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(8732, 10))

In [17]:
Y.shape

(8732, 10)

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=42)

In [19]:
X_train.shape
Y_train.shape
Y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], shape=(6549, 10))

In [20]:
#ann will be used
import tensorflow
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Dropout,Input
from tensorflow.keras.optimizers import RMSprop

In [21]:
model=Sequential()
model.add(Input(shape=(39,)))
model.add(Dense(256,activation="relu"))
model.add(Dropout(.25))
model.add(Dense(128,activation="relu"))
model.add(Dropout(.25))
model.add(Dense(64,activation="relu"))
model.add(Dropout(.25))
model.add(Dense(10,activation="softmax"))

In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 256)                 │          10,240 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 256)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 52,042 (203.29 KB)

 Trainable params: 52,042 (203.29 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.compile(optimizer=RMSprop(),loss="categorical_crossentropy",metrics=["accuracy"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [24]:
model.fit(X_train,Y_train,verbose=2,epochs=100,batch_size=100,validation_data=(X_test,Y_test))

Epoch 1/100
66/66 - 1s - 22ms/step - accuracy: 0.1634 - loss: 4.9619 - val_accuracy: 0.2602 - val_loss: 2.0786
Epoch 2/100
66/66 - 0s - 4ms/step - accuracy: 0.2239 - loss: 2.2258 - val_accuracy: 0.3294 - val_loss: 1.9282
Epoch 3/100
66/66 - 0s - 4ms/step - accuracy: 0.2994 - loss: 1.9984 - val_accuracy: 0.4769 - val_loss: 1.6761
Epoch 4/100
66/66 - 0s - 4ms/step - accuracy: 0.3514 - loss: 1.8357 - val_accuracy: 0.4856 - val_loss: 1.5939
Epoch 5/100
66/66 - 0s - 4ms/step - accuracy: 0.4233 - loss: 1.6712 - val_accuracy: 0.5442 - val_loss: 1.4187
Epoch 6/100
66/66 - 0s - 4ms/step - accuracy: 0.4665 - loss: 1.5738 - val_accuracy: 0.5996 - val_loss: 1.2979
Epoch 7/100
66/66 - 0s - 4ms/step - accuracy: 0.5120 - loss: 1.4463 - val_accuracy: 0.5918 - val_loss: 1.2073
Epoch 8/100
66/66 - 0s - 4ms/step - accuracy: 0.5353 - loss: 1.3729 - val_accuracy: 0.6468 - val_loss: 1.1224
Epoch 9/100
66/66 - 0s - 4ms/step - accuracy: 0.5683 - loss: 1.2849 - val_accuracy: 0.6807 - val_loss: 1.0364
Epoch 10/100
66/66 - 0s - 4ms/step - accuracy: 0.5986 - loss: 1.2074 - val_accuracy: 0.6972 - val_loss: 0.9656
Epoch 11/100
66/66 - 0s - 4ms/step - accuracy: 0.6170 - loss: 1.1470 - val_accuracy: 0.7013 - val_loss: 0.9169
Epoch 12/100
66/66 - 0s - 5ms/step - accuracy: 0.6381 - loss: 1.0845 - val_accuracy: 0.7197 - val_loss: 0.8703
Epoch 13/100
66/66 - 0s - 4ms/step - accuracy: 0.6599 - loss: 1.0282 - val_accuracy: 0.7371 - val_loss: 0.8175
Epoch 14/100
66/66 - 0s - 4ms/step - accuracy: 0.6697 - loss: 0.9992 - val_accuracy: 0.7604 - val_loss: 0.7655
Epoch 15/100
66/66 - 0s - 4ms/step - accuracy: 0.6827 - loss: 0.9470 - val_accuracy: 0.7664 - val_loss: 0.7520
Epoch 16/100
66/66 - 0s - 5ms/step - accuracy: 0.7015 - loss: 0.9022 - val_accuracy: 0.7623 - val_loss: 0.6956
Epoch 17/100
66/66 - 0s - 4ms/step - accuracy: 0.7158 - loss: 0.8566 - val_accuracy: 0.7852 - val_loss: 0.6656
Epoch 18/100
66/66 - 0s - 5ms/step - accuracy: 0.7204 - loss: 0.8414 - val_accuracy: 0.7934 - val_loss: 0.6364
Epoch 19/100
66/66 - 0s - 4ms/step - accuracy: 0.7313 - loss: 0.7935 - val_accuracy: 0.7948 - val_loss: 0.6315
Epoch 20/100
66/66 - 0s - 4ms/step - accuracy: 0.7403 - loss: 0.7760 - val_accuracy: 0.8108 - val_loss: 0.5993
Epoch 21/100
66/66 - 0s - 4ms/step - accuracy: 0.7552 - loss: 0.7394 - val_accuracy: 0.8158 - val_loss: 0.5947
Epoch 22/100
66/66 - 0s - 5ms/step - accuracy: 0.7665 - loss: 0.7035 - val_accuracy: 0.8181 - val_loss: 0.5684
Epoch 23/100
66/66 - 0s - 5ms/step - accuracy: 0.7678 - loss: 0.7032 - val_accuracy: 0.8241 - val_loss: 0.5493
Epoch 24/100
66/66 - 0s - 4ms/step - accuracy: 0.7766 - loss: 0.6732 - val_accuracy: 0.8291 - val_loss: 0.5442
Epoch 25/100
66/66 - 0s - 5ms/step - accuracy: 0.7804 - loss: 0.6593 - val_accuracy: 0.8378 - val_loss: 0.5285
Epoch 26/100
66/66 - 0s - 4ms/step - accuracy: 0.7919 - loss: 0.6391 - val_accuracy: 0.8278 - val_loss: 0.5299
Epoch 27/100
66/66 - 0s - 5ms/step - accuracy: 0.7902 - loss: 0.6255 - val_accuracy: 0.8410 - val_loss: 0.5235
Epoch 28/100
66/66 - 0s - 4ms/step - accuracy: 0.8061 - loss: 0.5843 - val_accuracy: 0.8447 - val_loss: 0.4943
Epoch 29/100
66/66 - 0s - 5ms/step - accuracy: 0.8058 - loss: 0.5909 - val_accuracy: 0.8493 - val_loss: 0.4946
Epoch 30/100
66/66 - 0s - 4ms/step - accuracy: 0.8047 - loss: 0.5740 - val_accuracy: 0.8516 - val_loss: 0.4733
Epoch 31/100
66/66 - 0s - 5ms/step - accuracy: 0.8157 - loss: 0.5514 - val_accuracy: 0.8488 - val_loss: 0.4828
Epoch 32/100
66/66 - 0s - 5ms/step - accuracy: 0.8119 - loss: 0.5598 - val_accuracy: 0.8548 - val_loss: 0.4580
Epoch 33/100
66/66 - 0s - 4ms/step - accuracy: 0.8235 - loss: 0.5278 - val_accuracy: 0.8612 - val_loss: 0.4606
Epoch 34/100
66/66 - 0s - 4ms/step - accuracy: 0.8188 - loss: 0.5235 - val_accuracy: 0.8676 - val_loss: 0.4610
Epoch 35/100
66/66 - 0s - 4ms/step - accuracy: 0.8247 - loss: 0.5274 - val_accuracy: 0.8626 - val_loss: 0.4632
Epoch 36/100
66/66 - 0s - 5ms/step - accuracy: 0.8311 - loss: 0.5059 - val_accuracy: 0.8635 - val_loss: 0.4585
Epoch 37/100
66/66 - 0s - 5ms/step - accuracy: 0.8311 - loss: 0.4876 - val_accuracy: 0.8694 - val_loss: 0.4395
Epoch 38/100
66/66 - 0s - 5ms/step - accuracy: 0.8400 - loss: 0.4795 - val_accuracy: 0.8644 - val_loss: 0.4545
Epoch 39/100
66/66 - 0s - 4ms/step - accuracy: 0.8397 - loss: 0.4752 - val_accuracy: 0.8699 - val_loss: 0.4482
Epoch 40/100
66/66 - 0s - 4ms/step - accuracy: 0.8395 - loss: 0.4805 - val_accuracy: 0.8694 - val_loss: 0.4510
Epoch 41/100
66/66 - 0s - 4ms/step - accuracy: 0.8429 - loss: 0.4616 - val_accuracy: 0.8731 - val_loss: 0.4202
Epoch 42/100
66/66 - 0s - 4ms/step - accuracy: 0.8449 - loss: 0.4668 - val_accuracy: 0.8713 - val_loss: 0.4250
Epoch 43/100
66/66 - 0s - 4ms/step - accuracy: 0.8530 - loss: 0.4389 - val_accuracy: 0.8763 - val_loss: 0.4293
Epoch 44/100
66/66 - 0s - 4ms/step - accuracy: 0.8578 - loss: 0.4352 - val_accuracy: 0.8727 - val_loss: 0.4254
Epoch 45/100
66/66 - 0s - 4ms/step - accuracy: 0.8569 - loss: 0.4268 - val_accuracy: 0.8777 - val_loss: 0.4335
Epoch 46/100
66/66 - 0s - 4ms/step - accuracy: 0.8578 - loss: 0.4233 - val_accuracy: 0.8850 - val_loss: 0.4067
Epoch 47/100
66/66 - 0s - 4ms/step - accuracy: 0.8601 - loss: 0.4258 - val_accuracy: 0.8896 - val_loss: 0.4091
Epoch 48/100
66/66 - 0s - 5ms/step - accuracy: 0.8641 - loss: 0.4091 - val_accuracy: 0.8891 - val_loss: 0.4099
Epoch 49/100
66/66 - 0s - 4ms/step - accuracy: 0.8676 - loss: 0.4067 - val_accuracy: 0.8786 - val_loss: 0.4087
Epoch 50/100
66/66 - 0s - 4ms/step - accuracy: 0.8664 - loss: 0.4053 - val_accuracy: 0.8882 - val_loss: 0.4063
Epoch 51/100
66/66 - 0s - 4ms/step - accuracy: 0.8624 - loss: 0.4157 - val_accuracy: 0.8864 - val_loss: 0.4181
Epoch 52/100
66/66 - 0s - 4ms/step - accuracy: 0.8659 - loss: 0.3894 - val_accuracy: 0.8814 - val_loss: 0.4143
Epoch 53/100
66/66 - 0s - 4ms/step - accuracy: 0.8728 - loss: 0.3804 - val_accuracy: 0.8887 - val_loss: 0.4122
Epoch 54/100
66/66 - 0s - 5ms/step - accuracy: 0.8713 - loss: 0.3901 - val_accuracy: 0.8855 - val_loss: 0.4046
Epoch 55/100
66/66 - 0s - 4ms/step - accuracy: 0.8711 - loss: 0.3839 - val_accuracy: 0.8869 - val_loss: 0.3950
Epoch 56/100
66/66 - 0s - 4ms/step - accuracy: 0.8748 - loss: 0.3877 - val_accuracy: 0.8878 - val_loss: 0.4146
Epoch 57/100
66/66 - 0s - 4ms/step - accuracy: 0.8754 - loss: 0.3777 - val_accuracy: 0.8978 - val_loss: 0.4026
Epoch 58/100
66/66 - 0s - 4ms/step - accuracy: 0.8774 - loss: 0.3714 - val_accuracy: 0.8919 - val_loss: 0.4045
Epoch 59/100
66/66 - 0s - 4ms/step - accuracy: 0.8803 - loss: 0.3608 - val_accuracy: 0.8933 - val_loss: 0.4135
Epoch 60/100
66/66 - 0s - 4ms/step - accuracy: 0.8814 - loss: 0.3581 - val_accuracy: 0.8891 - val_loss: 0.4032
Epoch 61/100
66/66 - 0s - 5ms/step - accuracy: 0.8820 - loss: 0.3496 - val_accuracy: 0.8914 - val_loss: 0.4252
Epoch 62/100
66/66 - 0s - 4ms/step - accuracy: 0.8792 - loss: 0.3692 - val_accuracy: 0.8942 - val_loss: 0.3914
Epoch 63/100
66/66 - 0s - 4ms/step - accuracy: 0.8844 - loss: 0.3557 - val_accuracy: 0.8914 - val_loss: 0.3902
Epoch 64/100
66/66 - 0s - 5ms/step - accuracy: 0.8812 - loss: 0.3560 - val_accuracy: 0.9001 - val_loss: 0.3741
Epoch 65/100
66/66 - 0s - 4ms/step - accuracy: 0.8824 - loss: 0.3565 - val_accuracy: 0.8873 - val_loss: 0.4124
Epoch 66/100
66/66 - 0s - 4ms/step - accuracy: 0.8896 - loss: 0.3565 - val_accuracy: 0.8901 - val_loss: 0.4227
Epoch 67/100
66/66 - 0s - 4ms/step - accuracy: 0.8833 - loss: 0.3662 - val_accuracy: 0.8919 - val_loss: 0.3964
Epoch 68/100
66/66 - 0s - 4ms/step - accuracy: 0.8916 - loss: 0.3374 - val_accuracy: 0.8965 - val_loss: 0.4091
Epoch 69/100
66/66 - 0s - 5ms/step - accuracy: 0.8893 - loss: 0.3340 - val_accuracy: 0.8887 - val_loss: 0.4136
Epoch 70/100
66/66 - 0s - 4ms/step - accuracy: 0.8937 - loss: 0.3348 - val_accuracy: 0.8923 - val_loss: 0.3997
Epoch 71/100
66/66 - 0s - 4ms/step - accuracy: 0.8945 - loss: 0.3138 - val_accuracy: 0.8923 - val_loss: 0.3997
Epoch 72/100
66/66 - 0s - 5ms/step - accuracy: 0.8937 - loss: 0.3268 - val_accuracy: 0.8928 - val_loss: 0.3970
Epoch 73/100
66/66 - 0s - 4ms/step - accuracy: 0.8971 - loss: 0.3168 - val_accuracy: 0.9020 - val_loss: 0.4021
Epoch 74/100
66/66 - 0s - 5ms/step - accuracy: 0.8954 - loss: 0.3202 - val_accuracy: 0.8988 - val_loss: 0.3799
Epoch 75/100
66/66 - 0s - 5ms/step - accuracy: 0.9021 - loss: 0.3014 - val_accuracy: 0.8910 - val_loss: 0.4175
Epoch 76/100
66/66 - 0s - 4ms/step - accuracy: 0.8994 - loss: 0.3247 - val_accuracy: 0.9011 - val_loss: 0.4183
Epoch 77/100
66/66 - 0s - 4ms/step - accuracy: 0.9020 - loss: 0.3018 - val_accuracy: 0.8928 - val_loss: 0.4309
Epoch 78/100
66/66 - 0s - 4ms/step - accuracy: 0.9044 - loss: 0.3097 - val_accuracy: 0.9033 - val_loss: 0.4050
Epoch 79/100
66/66 - 0s - 4ms/step - accuracy: 0.8991 - loss: 0.3110 - val_accuracy: 0.9020 - val_loss: 0.4082
Epoch 80/100
66/66 - 0s - 4ms/step - accuracy: 0.9027 - loss: 0.2914 - val_accuracy: 0.9006 - val_loss: 0.4027
Epoch 81/100
66/66 - 0s - 4ms/step - accuracy: 0.8969 - loss: 0.3137 - val_accuracy: 0.9029 - val_loss: 0.3994
Epoch 82/100
66/66 - 0s - 4ms/step - accuracy: 0.9055 - loss: 0.2916 - val_accuracy: 0.9015 - val_loss: 0.3955
Epoch 83/100
66/66 - 0s - 5ms/step - accuracy: 0.9066 - loss: 0.2952 - val_accuracy: 0.9070 - val_loss: 0.4094
Epoch 84/100
66/66 - 0s - 4ms/step - accuracy: 0.9029 - loss: 0.3055 - val_accuracy: 0.8974 - val_loss: 0.4134
Epoch 85/100
66/66 - 0s - 4ms/step - accuracy: 0.9026 - loss: 0.3120 - val_accuracy: 0.9020 - val_loss: 0.3996
Epoch 86/100
66/66 - 0s - 4ms/step - accuracy: 0.9093 - loss: 0.2946 - val_accuracy: 0.9024 - val_loss: 0.3908
Epoch 87/100
66/66 - 0s - 4ms/step - accuracy: 0.9099 - loss: 0.2951 - val_accuracy: 0.9043 - val_loss: 0.3965
Epoch 88/100
66/66 - 0s - 4ms/step - accuracy: 0.9066 - loss: 0.2925 - val_accuracy: 0.9029 - val_loss: 0.4160
Epoch 89/100
66/66 - 0s - 4ms/step - accuracy: 0.9058 - loss: 0.2853 - val_accuracy: 0.8983 - val_loss: 0.4310
Epoch 90/100
66/66 - 0s - 4ms/step - accuracy: 0.9062 - loss: 0.3062 - val_accuracy: 0.9015 - val_loss: 0.4245
Epoch 91/100
66/66 - 0s - 5ms/step - accuracy: 0.9076 - loss: 0.2922 - val_accuracy: 0.9066 - val_loss: 0.3971
Epoch 92/100
66/66 - 0s - 4ms/step - accuracy: 0.9108 - loss: 0.2773 - val_accuracy: 0.8997 - val_loss: 0.4161
Epoch 93/100
66/66 - 0s - 4ms/step - accuracy: 0.9090 - loss: 0.2779 - val_accuracy: 0.9033 - val_loss: 0.4276
Epoch 94/100
66/66 - 0s - 4ms/step - accuracy: 0.9095 - loss: 0.2969 - val_accuracy: 0.9011 - val_loss: 0.4199
Epoch 95/100
66/66 - 0s - 4ms/step - accuracy: 0.9096 - loss: 0.2830 - val_accuracy: 0.9056 - val_loss: 0.4084
Epoch 96/100
66/66 - 0s - 4ms/step - accuracy: 0.9148 - loss: 0.2606 - val_accuracy: 0.9038 - val_loss: 0.4075
Epoch 97/100
66/66 - 0s - 5ms/step - accuracy: 0.9064 - loss: 0.2882 - val_accuracy: 0.9001 - val_loss: 0.3976
Epoch 98/100
66/66 - 0s - 4ms/step - accuracy: 0.9136 - loss: 0.2659 - val_accuracy: 0.9061 - val_loss: 0.4008
Epoch 99/100
66/66 - 0s - 4ms/step - accuracy: 0.9114 - loss: 0.2730 - val_accuracy: 0.9038 - val_loss: 0.4064
Epoch 100/100
66/66 - 0s - 5ms/step - accuracy: 0.9102 - loss: 0.2757 - val_accuracy: 0.8992 - val_loss: 0.4261

In [25]:
test_accuracy=model.evaluate(X_test,Y_test)
test_accuracy[1]

69/69 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8992 - loss: 0.4261

0.8992212414741516

In [26]:
filename="UrbanSound8k/unknown.wav"
prediction_feature=feature_extractor(filename)
prediction_feature=prediction_feature.reshape(1,-1)
pred=model.predict(prediction_feature)
predicted_class = np.argmax(pred, axis=1)
print(predicted_class)
label=le.inverse_transform(predicted_class)
print(label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
[9]
['street_music']

In [27]:
prediction_feature.shape

(1, 39)